---
- name: Create EC2 Instance
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Create EC2 Instance
      ec2_instance:
        key_name: "{{ lookup('aws_ssm',  region='us-east-1') }}"
        security_group: "{{ security_group }}"
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        instance_tags:
          Name: "{{ instance_name }}"
        wait: true
        count: 1
        assign_public_ip: true
        user_data: |
          #!/bin/bash
          yum update -y
          yum install httpd -y
          systemctl start httpd
          systemctl enable httpd
          echo "<html><body><h1>Hello Ansible Tower</h1></body></html>" > /var/www/html/index.html
      register: ec2_instance

    - name: Print EC2 Instance Details
      debug:
        var: ec2_instance